// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pravesh.API.Data;

#nullable disable

namespace Pravesh.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627062534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pravesh.API.Entities.EntryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DenyReason")
                        .HasColumnType("longtext")
                        .HasColumnName("deny_reason");

                    b.Property<int?>("GateId")
                        .HasColumnType("int")
                        .HasColumnName("gate_id");

                    b.Property<int?>("GuardId")
                        .HasColumnType("int")
                        .HasColumnName("guard_id");

                    b.Property<int>("PassId")
                        .HasColumnType("int")
                        .HasColumnName("pass_id");

                    b.Property<bool>("ResidentNotified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("resident_notified");

                    b.Property<string>("ScanResult")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scan_result");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scanned_at");

                    b.Property<string>("UuidScanned")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("uuid_scanned");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.HasIndex("GuardId");

                    b.HasIndex("PassId");

                    b.ToTable("entry_logs");
                });

            modelBuilder.Entity("Pravesh.API.Entities.Flat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlatNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("flat_number");

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<int>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("society_id");

                    b.Property<string>("Tower")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tower");

                    b.HasKey("Id");

                    b.HasIndex("SocietyId", "FlatNumber")
                        .IsUnique();

                    b.ToTable("flats");
                });

            modelBuilder.Entity("Pravesh.API.Entities.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedGuardId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_guard_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("society_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedGuardId");

                    b.HasIndex("SocietyId");

                    b.ToTable("gates");
                });

            modelBuilder.Entity("Pravesh.API.Entities.Society", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("societies");
                });

            modelBuilder.Entity("Pravesh.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("FlatId")
                        .HasColumnType("int")
                        .HasColumnName("flat_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("society_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FlatId")
                        .IsUnique();

                    b.HasIndex("SocietyId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Pravesh.API.Entities.VisitorPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FlatId")
                        .HasColumnType("int")
                        .HasColumnName("flat_id");

                    b.Property<string>("PassType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pass_type");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int")
                        .HasColumnName("resident_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("UsesAllowed")
                        .HasColumnType("int")
                        .HasColumnName("uses_allowed");

                    b.Property<int>("UsesRemaining")
                        .HasColumnType("int")
                        .HasColumnName("uses_remaining");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("valid_until");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("visitor_name");

                    b.Property<string>("VisitorPhone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("visitor_phone");

                    b.HasKey("Id");

                    b.HasIndex("FlatId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("visitor_passes");
                });

            modelBuilder.Entity("Pravesh.API.Entities.EntryLog", b =>
                {
                    b.HasOne("Pravesh.API.Entities.Gate", "Gate")
                        .WithMany("EntryLogs")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pravesh.API.Entities.User", "Guard")
                        .WithMany("EntryLogs")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pravesh.API.Entities.VisitorPass", "VisitorPass")
                        .WithMany("EntryLogs")
                        .HasForeignKey("PassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gate");

                    b.Navigation("Guard");

                    b.Navigation("VisitorPass");
                });

            modelBuilder.Entity("Pravesh.API.Entities.Flat", b =>
                {
                    b.HasOne("Pravesh.API.Entities.Society", "Society")
                        .WithMany("Flats")
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Society");
                });

            modelBuilder.Entity("Pravesh.API.Entities.Gate", b =>
                {
                    b.HasOne("Pravesh.API.Entities.User", "AssignedGuard")
                        .WithMany()
                        .HasForeignKey("AssignedGuardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pravesh.API.Entities.Society", "Society")
                        .WithMany("Gates")
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedGuard");

                    b.Navigation("Society");
                });

            modelBuilder.Entity("Pravesh.API.Entities.Society", b =>
                {
                    b.HasOne("Pravesh.API.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Pravesh.API.Entities.User", b =>
                {
                    b.HasOne("Pravesh.API.Entities.Flat", "Flat")
                        .WithOne("Resident")
                        .HasForeignKey("Pravesh.API.Entities.User", "FlatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pravesh.API.Entities.Society", "Society")
                        .WithMany("Users")
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Flat");

                    b.Navigation("Society");
                });

            modelBuilder.Entity("Pravesh.API.Entities.VisitorPass", b =>
                {
                    b.HasOne("Pravesh.API.Entities.Flat", "Flat")
                        .WithMany("VisitorPasses")
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pravesh.API.Entities.User", "Resident")
                        .WithMany("VisitorPasses")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flat");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Pravesh.API.Entities.Flat", b =>
                {
                    b.Navigation("Resident");

                    b.Navigation("VisitorPasses");
                });

            modelBuilder.Entity("Pravesh.API.Entities.Gate", b =>
                {
                    b.Navigation("EntryLogs");
                });

            modelBuilder.Entity("Pravesh.API.Entities.Society", b =>
                {
                    b.Navigation("Flats");

                    b.Navigation("Gates");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pravesh.API.Entities.User", b =>
                {
                    b.Navigation("EntryLogs");

                    b.Navigation("VisitorPasses");
                });

            modelBuilder.Entity("Pravesh.API.Entities.VisitorPass", b =>
                {
                    b.Navigation("EntryLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
